name: book_store
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.1
  fluttertoast: ^8.2.1
  get_it: ^7.2.0
  go_router: ^6.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/errors/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/assets/
  filename: assets.dart

  fonts:
    - family: Sectra
      fonts:
        - asset: assets/fonts/GT-Sectra-Fine-Regular.ttf
          style: normal
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat.regular.ttf
          style: normal
